apiVersion: apps/v1
kind: Deployment
metadata:
  name: sauravabhang-eta-deploy
  labels:
    app: sauravabhang-eta-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sauravabhang-eta-app
  template:
    metadata:
      labels:
        app: sauravabhang-eta-app
    spec:
      containers:
      - name: sauravabhang-eta-container
        image: sauravabhangeta/sa-mywebapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: sauravabhang-eta-np-service
  labels:
    app: sauravabhang-eta-np-app
spec:
  selector:
    app: sauravabhang-eta-deploy-lbl
 
  type: NodePort
  ports:
  - nodePort: 31030
    port: 8080
    targetPort: 8080
