apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsw210-eta-deploy
  labels:
    app: vsw210-eta-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vsw210-eta-app
  template:
    metadata:
      labels:
        app: vsw210-eta-app
    spec:
      containers:
      - name: vsw210-eta-container
        image: vsw210eta/sa-mywebapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: vsw210-eta-np-service
  labels:
    app: vsw210-eta-np-app
spec:
  selector:
    app: vsw210-eta-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
    port: 8080
    targetPort: 8080
